import { MessageSquarePlus, Code2, Users, DollarSign } from "lucide-react";

const steps = [
  {
    icon: MessageSquarePlus,
    title: "Create a market",
    description: "Paste a URL, type a question, or describe an event. Our AI refines it into a tradeable prediction market in seconds.",
  },
  {
    icon: Code2,
    title: "Grab the embed",
    description: "Copy a tiny embed snippet — works as an iframe, JS widget, or rich-link preview for messaging apps.",
  },
  {
    icon: Users,
    title: "Your audience trades",
    description: "Viewers see live probabilities and trade directly inside the content they're already reading or watching.",
  },
  {
    icon: DollarSign,
    title: "You earn",
    description: "Creators receive 5–15% of trading volume generated by markets they launch. Passive income tied to your influence.",
  },
];

export function HowItWorks() {
  return (
    <section className="py-20">
      <div className="container">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            How it works
          </h2>
          <p className="text-muted-foreground text-lg max-w-xl mx-auto">
            From question to live prediction market in under 60 seconds.
          </p>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8">
          {steps.map((step, i) => (
            <div key={i} className="relative text-center group">
              <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-5 group-hover:bg-primary/20 transition-colors">
                <step.icon className="w-7 h-7 text-primary" />
              </div>
              <div className="absolute -top-2 -left-2 w-7 h-7 rounded-full bg-foreground text-background text-xs font-bold flex items-center justify-center">
                {i + 1}
              </div>
              <h3 className="font-semibold text-foreground mb-2">{step.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{step.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
