// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-markets.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/logging.ts
function withLogging(toolName, handler) {
  return async (input, ctx) => {
    const startedAt = Date.now();
    let result;
    let thrown = null;
    try {
      result = await handler(input, ctx);
    } catch (err) {
      thrown = err;
      result = {
        content: [{ type: "text", text: err instanceof Error ? err.message : "Tool failed" }],
        isError: true
      };
    }
    const durationMs = Date.now() - startedAt;
    const success = !thrown && !result.isError;
    const errorMessage = success ? null : thrown instanceof Error ? thrown.message : result.content?.[0]?.text ?? "Unknown error";
    try {
      if (ctx.isAuthenticated?.()) {
        await supabaseForUser(ctx).from("mcp_tool_logs").insert({
          user_id: ctx.getUserId(),
          tool_name: toolName,
          client_id: ctx.getClientId?.() ?? null,
          arguments: input ?? {},
          success,
          error_message: errorMessage,
          duration_ms: durationMs
        });
      }
    } catch {
    }
    return result;
  };
}

// src/lib/mcp/tools/list-markets.ts
var list_markets_default = defineTool({
  name: "list_markets",
  title: "List markets",
  description: "List active prediction markets, optionally filtered by category or a text search on the question.",
  inputSchema: {
    category: z.string().trim().min(1).optional().describe("Category filter, e.g. crypto."),
    search: z.string().trim().min(1).optional().describe("Text to match in the market question."),
    limit: z.number().int().min(1).max(50).optional().describe("Max markets to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withLogging("list_markets", async ({ category, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("markets").select("id,question,category,status,yes_odds,no_odds,volume,end_date,engine").eq("status", "active").gt("end_date", (/* @__PURE__ */ new Date()).toISOString()).order("volume", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.eq("category", category);
    if (search) query = query.ilike("question", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { markets: data ?? [] }
    };
  })
});

// src/lib/mcp/tools/get-market.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_market_default = defineTool2({
  name: "get_market",
  title: "Get market",
  description: "Get one prediction market by id, including current YES/NO odds, volume, resolution status and recent order book depth.",
  inputSchema: { market_id: z2.string().uuid().describe("The market id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withLogging("get_market", async ({ market_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: market, error } = await supabase.from("markets").select("*").eq("id", market_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!market) return { content: [{ type: "text", text: "Market not found" }], isError: true };
    const { data: book } = await supabase.from("order_book").select("side,contract,price,quantity,filled,status").eq("market_id", market_id).eq("status", "open").order("price", { ascending: false }).limit(50);
    const payload = { market, order_book: book ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  })
});

// src/lib/mcp/tools/get-portfolio.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_portfolio_default = defineTool3({
  name: "get_portfolio",
  title: "Get portfolio",
  description: "Get the signed-in user's demo balance, open bets and CLOB positions across all markets.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withLogging("get_portfolio", async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    const [{ data: profile }, { data: bets }, { data: positions }] = await Promise.all([
      supabase.from("profiles").select("balance").eq("id", userId).maybeSingle(),
      supabase.from("bets").select("id,market_id,option,amount,odds,potential_payout,status,created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(50),
      supabase.from("positions").select("market_id,yes_qty,no_qty").eq("user_id", userId)
    ]);
    const payload = {
      balance: profile?.balance ?? 0,
      bets: bets ?? [],
      positions: positions ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  })
});

// src/lib/mcp/tools/place-bet.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var place_bet_default = defineTool4({
  name: "place_bet",
  title: "Place bet",
  description: "Place a bet as the signed-in user on an AMM market outcome (Yes or No) for a given amount of demo balance.",
  inputSchema: {
    market_id: z3.string().uuid().describe("The market to bet on."),
    option: z3.enum(["Yes", "No"]).describe("Outcome to back."),
    amount: z3.number().positive().max(1e4).describe("Stake amount in demo balance.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: withLogging("place_bet", async ({ market_id, option, amount }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("place_bet", {
      p_market_id: market_id,
      p_user_id: ctx.getUserId(),
      p_option: option,
      p_amount: amount
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { result: data }
    };
  })
});

// src/lib/mcp/tools/place-limit-order.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var place_limit_order_default = defineTool5({
  name: "place_limit_order",
  title: "Place limit order",
  description: "Place a resting limit order on a CLOB market as the signed-in user (BUY/SELL of a YES or NO contract at a price between 0.01 and 0.99).",
  inputSchema: {
    market_id: z4.string().uuid().describe("CLOB market id."),
    side: z4.enum(["BUY", "SELL"]).describe("Order side."),
    contract: z4.enum(["YES", "NO"]).describe("Contract to trade."),
    price: z4.number().min(0.01).max(0.99).describe("Limit price in dollars per contract."),
    quantity: z4.number().positive().max(1e5).describe("Number of contracts.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: withLogging("place_limit_order", async ({ market_id, side, contract, price, quantity }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("place_limit_order", {
      p_market_id: market_id,
      p_side: side,
      p_contract: contract,
      p_price: price,
      p_quantity: quantity
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { result: data }
    };
  })
});

// src/lib/mcp/tools/cancel-order.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var cancel_order_default = defineTool6({
  name: "cancel_order",
  title: "Cancel order",
  description: "Cancel one of the signed-in user's open limit orders and refund its collateral.",
  inputSchema: { order_id: z5.string().uuid().describe("The order id to cancel.") },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: withLogging("cancel_order", async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.rpc("cancel_order", { p_order_id: order_id });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Order ${order_id} cancelled.` }],
      structuredContent: { order_id, status: "cancelled" }
    };
  })
});

// src/lib/mcp/index.ts
var projectRef = "cwecrtmyhemghqzyywap";
var mcp_default = defineMcp({
  name: "kastia",
  title: "Kastia",
  version: "0.1.0",
  instructions: "Tools for Kastia, a prediction market platform. Browse active markets with `list_markets`, inspect odds and order book depth with `get_market`, review the signed-in user's balance, bets and positions with `get_portfolio`, and trade with `place_bet` (AMM markets), `place_limit_order` and `cancel_order` (CLOB markets).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_markets_default,
    get_market_default,
    get_portfolio_default,
    place_bet_default,
    place_limit_order_default,
    cancel_order_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
